### ISSUE TITLE
not found dwd.sh: 40

### ISSUE THREAD

**Issue by Lawmanwilly** [dl7ata/Scripte#1]
Hallo, i trying to set up the dwd.sh script. I keep getting this error not found dwd.sh: 40,
the folder /tmp/wx_msg is empty. I suspect this may be the problem that the files aren't downloading. Any tips for my at this point? 73 de Lawrence

**Comment by dl7ata** [comment]
The script is "dwd", without ending .sh
I copied the raw Github source and it works fine for me. The only thing is, for text-to-speech you need a googlge account. But as long as you use valid parameter for location, it create a file /tmp/wx_msg/.

**Comment by Lawmanwilly** [comment]
Ok in my 

sudo crontab -u svxlink -e  I have entered  
*/20 * * * * /home/svxlink/Wetter/dwd >> /tmp/dwd.log 2>&1

Thanks for the other info, where would i enter my google account info ?

**Comment by dl7ata** [comment]
Unfortunately the google service changed. So from section _ # TTS STart_ you need to create your own text-to-speech. A free service is [MARY](http://marytts.phonetik.uni-muenchen.de:59125/)
