### ISSUE TITLE
wx_warn.py

### ISSUE THREAD

**Issue by Lawmanwilly** [dl7ata/Scripte#2]
Ich habe eine frage, bin weiter gekommen mit dwd script. Kurz für Schluss ist 	   /home/svxlink/Wetter/wx_warn.py >> /tmp/wx_warn.tmp  
 (./dwd.sh: line 131: /home/svxlink/Wetter/wx_warn.py: No such file or directory)
wo & wie wird das wx_warn.py abgelegt ?  Danke & 73s de Lawrence

**Comment by dl7ata** [comment]
Hi Lawrence,

take care of the directories stated from line 109:
subprocess.call(["/home/svxlink/TTS/tts.sh",
                                     msg_text, "m"])
                    von = '/tmp/wx.wav'


That means "/home/svxlink/TTS/tts.sh" is the subprocess for test-to-message (WAV), "m" and "von" are parameter for that script. As long as you don't use TTS you can delete it.
Where you put dwd.py itself doens't matter.

Hope it helps!

Best
Frank
